export enum OptimizationType {
  ROUTE_OPTIMIZATION = 'ROUTE_OPTIMIZATION',
  DRIVER_ASSIGNMENT = 'DRIVER_ASSIGNMENT',
  RESTAURANT_ASSIGNMENT = 'RESTAURANT_ASSIGNMENT',
  CAPACITY_PLANNING = 'CAPACITY_PLANNING',
  DELIVERY_SCHEDULING = 'DELIVERY_SCHEDULING'
} 